name: BuyLand
version: 0.7.4
main: me.buyland.buyland.main
description: Buy, Sell and Rent WorldGuard Regions
authors: [chriztopia]
website: http://chriztopia.com
depend: [WorldGuard]
softdepend: [Vault]
commands:
  buyland:
    description: Buys WorldGuard Land
    usage: Error! Plugin Is Not Working! Command BuyLand.
  priceland:
    description: Checks Price of WorldGuard Land
    usage: Error! Plugin Is Not Working! Command PriceLand.
  sellland:
    description: Sell WorldGuard Land
    usage: Error! Plugin Is Not Working! Command SellLand.
  reloadbuyland:
    description: Reloads Land Config
    usage: Error! Plugin Is Not Working! Command ReloadBuyLand.
  abl:
    description: Admin Commands for BuyLand.
    usage: Error! Plugin Is Not Working! Command ABL.
  adminbuyland:
    description: Admin Commands for BuyLand.
    usage: Error! Plugin Is Not Working! Command AdminBuyLand.
  rentland:
    description: Rents you land.
    usage: Error! Plugin Is Not Working! Command RentLand.
permissions:
    buyland.buy:
        description: Buys a Region.
        default: op
    buyland.sell:
        description: Sells a Region.
        default: op
    buyland.rent:
        description: Rents a Region.
        default: op
    buyland.price:
        description: Prices a Region.
        default: op
    buyland.reload:
        description: Reload the Configs.
        default: op
    buyland.admin:
        description: Admin Commands for BuyLand.
        default: op
    buyland.all:
        description: All Commands.
        default: op
    buyland.signuse:
        description: Allowed use of BuyLand command signs.
        default: op
    buyland.signbreak:
        description: Allowed to Break Buyland command signs.
        default: op
    buyland.signcreate:
        description: Allowed to Create Buyland command signs.
        default: op
    buyland.buy.addmember:
        description: AddMember to region.
        default: op
    buyland.buy.removemember:
        description: RemoveMember from region.
        default: op
    buyland.rent.addmember:
        description: AddMember to rent region.
        default: op
    buyland.rent.removemember:
        description: RemoveMember from rent region.
        default: op 
    buyland.tp:
        description: Teleport to a regions sign.
        default: op
    buyland.list:
        description: List all owned regions.
        default: op
    buyland.admin.list:
        description: List all owned regions for a player.
        default: op 